name: CI
on: [push]

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Debug Session
        uses: csexton/debugger-action@v1

      - name: Run Tests
        run: npm test
